/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.CsAdjunto;
import com.incloud.hcp.domain.CsAdjunto_;
import com.incloud.hcp.domain.CsOrdenServicio;
import com.incloud.hcp.domain.MtrTipoDocumento;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface CsAdjuntoRepository extends JPACustomRepository<CsAdjunto, Long> {

    default List<CsAdjunto> findCompletePaginated(String query, int maxResults) {
        CsAdjunto probe = new CsAdjunto();
        //probe.setDocumentoRepositorioId(query);
        probe.setDocumentoRepositorioId(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(CsAdjunto_.documentoRepositorioId.getName(), match -> match.ignoreCase().startsWith());

        Page<CsAdjunto> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByMtrTipoDocumento(@Param("mtrTipoDocumento") MtrTipoDocumento mtrTipoDocumento);

    Long countByCsOrdenServicio(@Param("csOrdenServicio") CsOrdenServicio csOrdenServicio);

}
