/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.*;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface CsOrdenServicioRepository extends JPACustomRepository<CsOrdenServicio, Long> {

    default List<CsOrdenServicio> findCompletePaginated(String query, int maxResults) {
        CsOrdenServicio probe = new CsOrdenServicio();
        //probe.setNumeroOrdenServicio(query);
        probe.setNumeroOrdenServicio(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(CsOrdenServicio_.numeroOrdenServicio.getName(), match -> match.ignoreCase().startsWith());

        Page<CsOrdenServicio> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByMtrModalidadTrabajo(@Param("mtrModalidadTrabajo") MtrModalidadTrabajo mtrModalidadTrabajo);

    Long countByMtrTiempoEntrega(@Param("mtrTiempoEntrega") MtrTiempoEntrega mtrTiempoEntrega);

    Long countByMtrCalidadServicio(@Param("mtrCalidadServicio") MtrCalidadServicio mtrCalidadServicio);

    Long countByMtrEstado(@Param("mtrEstado") MtrEstado mtrEstado);

    Long countByMtrLugarTrabajo(@Param("mtrLugarTrabajo") MtrLugarTrabajo mtrLugarTrabajo);

    Long countByOdm(@Param("odm") Odm odm);

    Long countByMtrPuerto(@Param("mtrPuerto") MtrPuerto mtrPuerto);

    Long countByMtrSeguridad(@Param("mtrSeguridad") MtrSeguridad mtrSeguridad);

}
