/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.incloud.hcp.repository;

import com.incloud.hcp.domain.CsOrdenServicio;
import com.incloud.hcp.domain.CsRecomendacion;
import com.incloud.hcp.domain.CsRecomendacion_;
import com.incloud.hcp.repository._framework.JPACustomRepository;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.repository.NoRepositoryBean;
import org.springframework.data.repository.query.Param;

import java.util.List;

@NoRepositoryBean
public interface CsRecomendacionRepository extends JPACustomRepository<CsRecomendacion, Long> {

    default List<CsRecomendacion> findCompletePaginated(String query, int maxResults) {
        CsRecomendacion probe = new CsRecomendacion();
        //probe.setDescripcion(query);
        probe.setDescripcion(null);
        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(CsRecomendacion_.descripcion.getName(), match -> match.ignoreCase().startsWith());

        Page<CsRecomendacion> page = this.findAll(Example.of(probe, matcher), PageRequest.of(0, maxResults));
        return page.getContent();
    }

    Long countByCsOrdenServicio(@Param("csOrdenServicio") CsOrdenServicio csOrdenServicio);

}
