/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.common.graph.GraphBarChart;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.common.graph.GraphDataset;
import com.incloud.hcp.common.graph.GraphPieChart;
import com.incloud.hcp.domain.*;
import com.incloud.hcp.domain.response.CsAdjuntoResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.AppParametriaDeltaRepository;
import com.incloud.hcp.repository.delta.CsAdjuntoDeltaRepository;
import com.incloud.hcp.repository.delta.CsOrdenServicioDeltaRepository;
import com.incloud.hcp.repository.delta.MtrTipoDocumentoDeltaRepository;
import com.incloud.hcp.service.CsAdjuntoService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.delta.CsOrdenServicioDeltaService;
import com.incloud.hcp.service.delta.MtrTipoDocumentoDeltaService;
import com.incloud.hcp.service.requireNew.CsAdjuntoRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for CsAdjunto.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class CsAdjuntoServiceImpl extends JPACustomServiceImpl<CsAdjuntoResponse, CsAdjunto, Long> implements CsAdjuntoService {

    protected final String NAME_SHEET = "CsAdjunto";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/CsAdjuntoExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected CsAdjuntoDeltaRepository csAdjuntoDeltaRepository;

    @Autowired
    protected CsAdjuntoRequireNewService csAdjuntoRequireNewService;

    @Autowired
    protected MtrTipoDocumentoDeltaService mtrTipoDocumentoDeltaService;

    @Autowired
    protected MtrTipoDocumentoDeltaRepository mtrTipoDocumentoDeltaRepository;

    @Autowired
    protected CsOrdenServicioDeltaService csOrdenServicioDeltaService;

    @Autowired
    protected CsOrdenServicioDeltaRepository csOrdenServicioDeltaRepository;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
                .withMatcher(CsAdjunto_.numeroOds.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(CsAdjunto_.extension.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(CsAdjunto_.descProveedor.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(CsAdjunto_.documentoRepositorioId.getName(), match -> match.ignoreCase().startsWith());
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(CsAdjunto req, ExampleMatcher matcher, Example<CsAdjunto> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<CsAdjunto> req, ExampleMatcher matcher, Example<CsAdjunto> example);

    protected final CsAdjunto setObtenerBeanResponse(CsAdjuntoResponse bean) {
        return bean.getBean();
    }

    protected final Class<CsAdjunto> setObtenerClassBean() {
        return CsAdjunto.class;
    }

    protected List<Predicate> setAbstractPredicate(CsAdjuntoResponse bean, CriteriaBuilder cb, Root<CsAdjunto> root) {
        List<Predicate> predicates = new ArrayList<>();
        CsAdjunto entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getNumeroOdsCondicion(), "numeroOds", entity.getNumeroOds(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getExtensionCondicion(), "extension ", entity.getExtension (), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getDescProveedorCondicion(), "descProveedor", entity.getDescProveedor(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getDocumentoRepositorioIdCondicion(), "documentoRepositorioId", entity.getDocumentoRepositorioId(), cb, root);
        //PredicateUtils.addPredicates(predicates, bean.getMtrTipoDocumentoCondicion(), "mtrTipoDocumento", entity.getMtrTipoDocumento(), cb, root);
        //PredicateUtils.addPredicates(predicates, bean.getCsOrdenServicioCondicion(), "csOrdenServicio", entity.getCsOrdenServicio(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "numeroOds", bean.getNumeroOdsList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "extension ", bean.getExtensionList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "descProveedor", bean.getDescProveedorList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "documentoRepositorioId", bean.getDocumentoRepositorioIdList(), cb, root);
        //PredicateUtils.addPredicatesListValorBean(predicates, "mtrTipoDocumento", bean.getMtrTipoDocumentoList(), cb, root);
        //PredicateUtils.addPredicatesListValorBean(predicates, "csOrdenServicio", bean.getCsOrdenServicioList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(CsAdjunto bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getDocumentoRepositorioId()).isPresent()) {
            String msg = this.messageSource.getMessage("message.csAdjunto.documentoRepositorioId.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(CsAdjunto bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(CsAdjunto bean) throws Exception {
        String msg = null;
        CsAdjunto validar = null;
        return msg;
    }

    protected String validacionesPreviasSave(CsAdjunto bean) throws Exception {
        String msg = null;
        CsAdjunto validar = null;
        return msg;
    }

    protected CsAdjunto completarDatosBean(CsAdjunto bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected CsAdjunto setCompletarDatosBean(CsAdjunto bean) throws Exception {
        return bean;
    }

    protected final CsAdjunto setAbstractCreate(CsAdjunto dto) throws Exception {
        CsAdjunto bean = new CsAdjunto();
        bean = (CsAdjunto) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected CsAdjunto setUploadExcel(Cell currentCell, CsAdjunto csAdjunto, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 100) {
                    throw new ServiceException("Valor Campo numeroOds contiene mas de 100 caracter(es)");
                }
                csAdjunto.setNumeroOds(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo numeroOds está en formato incorrecto");
            }
            break;
        case 2:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 10) {
                    throw new ServiceException("Valor Campo extension  contiene mas de 10 caracter(es)");
                }
                csAdjunto.setExtension(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo extension  está en formato incorrecto");
            }
            break;
        case 3:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 100) {
                    throw new ServiceException("Valor Campo descProveedor contiene mas de 100 caracter(es)");
                }
                csAdjunto.setDescProveedor(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo descProveedor está en formato incorrecto");
            }
            break;
        case 4:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 50) {
                    throw new ServiceException("Valor Campo documentoRepositorioId contiene mas de 50 caracter(es)");
                }
                csAdjunto.setDocumentoRepositorioId(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo documentoRepositorioId está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return csAdjunto;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected CsAdjunto setInicializarBeanUpdateExcel() {
        CsAdjunto bean = new CsAdjunto();
        bean.setId(null);
        return bean;
    }

    protected final Long setObtenerId(CsAdjunto bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final CsAdjunto createInstance() {
        CsAdjunto csAdjunto = new CsAdjunto();
        return csAdjunto;
    }

    protected final BeanCargaMasivoDTO<CsAdjunto> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<CsAdjunto> beanCargaMasivoDTO = new BeanCargaMasivoDTO<CsAdjunto>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<CsAdjunto>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<CsAdjunto>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<CsAdjunto>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(CsAdjunto bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getNumeroOds(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getExtension(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getDescProveedor(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getDocumentoRepositorioId(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(CsAdjunto bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getNumeroOds(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getExtension(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getDescProveedor(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getDocumentoRepositorioId(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(CsAdjunto bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO CS_ADJUNTO(";
        sqlInsert = sqlInsert + "CS_ADJUNTO_ID" + ", ";
        sqlInsert = sqlInsert + "NUMERO_ODS" + ", ";
        sqlInsert = sqlInsert + "EXTENSION " + ", ";
        sqlInsert = sqlInsert + "DESC_PROVEEDOR" + ", ";
        sqlInsert = sqlInsert + "DOCUMENTO_REPOSITORIO_ID" + ", ";
        sqlInsert = sqlInsert + "MTR_TIPO_DOCUMENTO_ID" + ", ";
        sqlInsert = sqlInsert + "CS_ORDEN_SERVICIO_ID" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        if (StringUtils.isBlank(bean.getNumeroOds())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getNumeroOds() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getExtension())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getExtension() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getDescProveedor())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getDescProveedor() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getDocumentoRepositorioId())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getDocumentoRepositorioId() + "'" + ", ";
        }
        sqlInsert = sqlInsert + bean.getMtrTipoDocumento().getId() + ", ";
        sqlInsert = sqlInsert + bean.getCsOrdenServicio().getId();
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    public Long countByMtrTipoDocumento(MtrTipoDocumento mtrTipoDocumento) {
        return this.csAdjuntoDeltaRepository.countByMtrTipoDocumento(mtrTipoDocumento);
    }

    public GraphBean graphByMtrTipoDocumento() {
        List<MtrTipoDocumento> lista = this.mtrTipoDocumentoDeltaRepository.findAll();
        if (lista == null || lista.size() <= 0) {
            return null;
        }
        GraphBean graphBean = new GraphBean();

        /* Obteniendo Pie Chart */
        GraphPieChart graphPieChart = new GraphPieChart();
        GraphDataset graphDataset = new GraphDataset();
        GraphDataset[] listaGraphDataset = new GraphDataset[1];
        Long[] data = new Long[lista.size()];
        String[] labels = new String[lista.size()];
        String[] backgroundColor = new String[lista.size()];
        String[] hoverBackgroundColor = new String[lista.size()];
        String[] borderColor = new String[lista.size()];
        String[] hoverBorderColor = new String[lista.size()];
        int contador = 0;
        int contadorColor = 0;
        for (MtrTipoDocumento bean : lista) {
            Long valor = this.csAdjuntoDeltaRepository.countByMtrTipoDocumento(bean);
            String descripcion = this.setGraphDescripcionByMtrTipoDocumento(bean);
            data[contador] = valor;
            labels[contador] = descripcion;
            backgroundColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }
        }
        String titulo = this.setGraphPieChartTituloByMtrTipoDocumento();
        graphDataset.setLabel(titulo);
        graphDataset.setData(data);
        graphDataset.setBackgroundColor(backgroundColor);
        graphDataset.setHoverBackgroundColor(hoverBackgroundColor);
        listaGraphDataset[0] = graphDataset;
        graphPieChart.setDatasets(listaGraphDataset);
        graphPieChart.setLabels(labels);
        graphBean.setPiechart(graphPieChart);

        GraphBarChart graphBarChart = new GraphBarChart();
        GraphDataset[] listaGraphDatasetBar = new GraphDataset[lista.size()];
        String[] labelsBar = new String[1];
        labelsBar[0] = this.setGraphBarChartTituloByMtrTipoDocumento();
        contador = 0;
        contadorColor = 0;
        for (MtrTipoDocumento bean : lista) {
            Long valor = this.csAdjuntoDeltaRepository.countByMtrTipoDocumento(bean);
            String descripcion = this.setGraphDescripcionByMtrTipoDocumento(bean);
            GraphDataset graphDatasetBar = new GraphDataset();
            Long[] dataBar = new Long[1];

            String[] backgroundColorBar = new String[1];
            String[] hoverBackgroundColorBar = new String[1];
            String[] borderColorBar = new String[1];
            String[] hoverBorderColorBar = new String[1];

            dataBar[0] = valor;
            backgroundColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];

            graphDatasetBar.setLabel(descripcion);
            graphDatasetBar.setData(dataBar);
            graphDatasetBar.setBackgroundColor(backgroundColorBar);
            graphDatasetBar.setHoverBackgroundColor(hoverBackgroundColorBar);
            graphDatasetBar.setBorderColor(borderColorBar);
            graphDatasetBar.setHoverBorderColor(hoverBorderColorBar);
            listaGraphDatasetBar[contador] = graphDatasetBar;

            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }

        }
        graphBarChart.setDatasets(listaGraphDatasetBar);
        graphBarChart.setLabels(labelsBar);
        graphBean.setBarchart(graphBarChart);
        return graphBean;
    }

    protected String setGraphDescripcionByMtrTipoDocumento(MtrTipoDocumento mtrTipoDocumento) {
        return mtrTipoDocumento.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrTipoDocumento() {
        return "MtrTipoDocumento";
    }

    protected String setGraphBarChartTituloByMtrTipoDocumento() {
        return "MtrTipoDocumento";
    }

    public Long countByCsOrdenServicio(CsOrdenServicio csOrdenServicio) {
        return this.csAdjuntoDeltaRepository.countByCsOrdenServicio(csOrdenServicio);
    }

    public GraphBean graphByCsOrdenServicio() {
        List<CsOrdenServicio> lista = this.csOrdenServicioDeltaRepository.findAll();
        if (lista == null || lista.size() <= 0) {
            return null;
        }
        GraphBean graphBean = new GraphBean();

        /* Obteniendo Pie Chart */
        GraphPieChart graphPieChart = new GraphPieChart();
        GraphDataset graphDataset = new GraphDataset();
        GraphDataset[] listaGraphDataset = new GraphDataset[1];
        Long[] data = new Long[lista.size()];
        String[] labels = new String[lista.size()];
        String[] backgroundColor = new String[lista.size()];
        String[] hoverBackgroundColor = new String[lista.size()];
        String[] borderColor = new String[lista.size()];
        String[] hoverBorderColor = new String[lista.size()];
        int contador = 0;
        int contadorColor = 0;
        for (CsOrdenServicio bean : lista) {
            Long valor = this.csAdjuntoDeltaRepository.countByCsOrdenServicio(bean);
            String descripcion = this.setGraphDescripcionByCsOrdenServicio(bean);
            data[contador] = valor;
            labels[contador] = descripcion;
            backgroundColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColor[contador] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColor[contador] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }
        }
        String titulo = this.setGraphPieChartTituloByCsOrdenServicio();
        graphDataset.setLabel(titulo);
        graphDataset.setData(data);
        graphDataset.setBackgroundColor(backgroundColor);
        graphDataset.setHoverBackgroundColor(hoverBackgroundColor);
        listaGraphDataset[0] = graphDataset;
        graphPieChart.setDatasets(listaGraphDataset);
        graphPieChart.setLabels(labels);
        graphBean.setPiechart(graphPieChart);

        GraphBarChart graphBarChart = new GraphBarChart();
        GraphDataset[] listaGraphDatasetBar = new GraphDataset[lista.size()];
        String[] labelsBar = new String[1];
        labelsBar[0] = this.setGraphBarChartTituloByCsOrdenServicio();
        contador = 0;
        contadorColor = 0;
        for (CsOrdenServicio bean : lista) {
            Long valor = this.csAdjuntoDeltaRepository.countByCsOrdenServicio(bean);
            String descripcion = this.setGraphDescripcionByCsOrdenServicio(bean);
            GraphDataset graphDatasetBar = new GraphDataset();
            Long[] dataBar = new Long[1];

            String[] backgroundColorBar = new String[1];
            String[] hoverBackgroundColorBar = new String[1];
            String[] borderColorBar = new String[1];
            String[] hoverBorderColorBar = new String[1];

            dataBar[0] = valor;
            backgroundColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBackgroundColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];
            borderColorBar[0] = Constants.BACKGROUND_COLOR_GRAPH[contadorColor];
            hoverBorderColorBar[0] = Constants.HOVER_BACKGROUND_COLOR_GRAPH[contadorColor];

            graphDatasetBar.setLabel(descripcion);
            graphDatasetBar.setData(dataBar);
            graphDatasetBar.setBackgroundColor(backgroundColorBar);
            graphDatasetBar.setHoverBackgroundColor(hoverBackgroundColorBar);
            graphDatasetBar.setBorderColor(borderColorBar);
            graphDatasetBar.setHoverBorderColor(hoverBorderColorBar);
            listaGraphDatasetBar[contador] = graphDatasetBar;

            contador++;
            contadorColor++;
            if (contadorColor >= REGISTROS_COLOR) {
                contadorColor = 1;
            }

        }
        graphBarChart.setDatasets(listaGraphDatasetBar);
        graphBarChart.setLabels(labelsBar);
        graphBean.setBarchart(graphBarChart);
        return graphBean;
    }

    protected String setGraphDescripcionByCsOrdenServicio(CsOrdenServicio csOrdenServicio) {
        return csOrdenServicio.getId().toString();
    }

    protected String setGraphPieChartTituloByCsOrdenServicio() {
        return "CsOrdenServicio";
    }

    protected String setGraphBarChartTituloByCsOrdenServicio() {
        return "CsOrdenServicio";
    }

}
