/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.domain.MtrModalidadTrabajo;
import com.incloud.hcp.domain.MtrModalidadTrabajo_;
import com.incloud.hcp.domain.response.MtrModalidadTrabajoResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.AppParametriaDeltaRepository;
import com.incloud.hcp.repository.delta.MtrModalidadTrabajoDeltaRepository;
import com.incloud.hcp.service.MtrModalidadTrabajoService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.requireNew.MtrModalidadTrabajoRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for MtrModalidadTrabajo.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class MtrModalidadTrabajoServiceImpl extends JPACustomServiceImpl<MtrModalidadTrabajoResponse, MtrModalidadTrabajo, Long>
        implements MtrModalidadTrabajoService {

    protected final String NAME_SHEET = "MtrModalidadTrabajo";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/MtrModalidadTrabajoExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected MtrModalidadTrabajoDeltaRepository mtrModalidadTrabajoDeltaRepository;

    @Autowired
    protected MtrModalidadTrabajoRequireNewService mtrModalidadTrabajoRequireNewService;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
                .withMatcher(MtrModalidadTrabajo_.descripcion.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(MtrModalidadTrabajo_.status.getName(), match -> match.ignoreCase().startsWith());
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(MtrModalidadTrabajo req, ExampleMatcher matcher, Example<MtrModalidadTrabajo> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<MtrModalidadTrabajo> req, ExampleMatcher matcher, Example<MtrModalidadTrabajo> example);

    protected final MtrModalidadTrabajo setObtenerBeanResponse(MtrModalidadTrabajoResponse bean) {
        return bean.getBean();
    }

    protected final Class<MtrModalidadTrabajo> setObtenerClassBean() {
        return MtrModalidadTrabajo.class;
    }

    protected List<Predicate> setAbstractPredicate(MtrModalidadTrabajoResponse bean, CriteriaBuilder cb, Root<MtrModalidadTrabajo> root) {
        List<Predicate> predicates = new ArrayList<>();
        MtrModalidadTrabajo entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getDescripcionCondicion(), "descripcion", entity.getDescripcion(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getStatusCondicion(), "status", entity.getStatus(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "descripcion", bean.getDescripcionList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "status", bean.getStatusList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(MtrModalidadTrabajo bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getDescripcion()).isPresent()) {
            String msg = this.messageSource.getMessage("message.mtrModalidadTrabajo.descripcion.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(MtrModalidadTrabajo bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(MtrModalidadTrabajo bean) throws Exception {
        String msg = null;
        MtrModalidadTrabajo validar = null;
        return msg;
    }

    protected String validacionesPreviasSave(MtrModalidadTrabajo bean) throws Exception {
        String msg = null;
        MtrModalidadTrabajo validar = null;
        return msg;
    }

    protected MtrModalidadTrabajo completarDatosBean(MtrModalidadTrabajo bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected MtrModalidadTrabajo setCompletarDatosBean(MtrModalidadTrabajo bean) throws Exception {
        return bean;
    }

    protected final MtrModalidadTrabajo setAbstractCreate(MtrModalidadTrabajo dto) throws Exception {
        MtrModalidadTrabajo bean = new MtrModalidadTrabajo();
        bean = (MtrModalidadTrabajo) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrModalidadTrabajo setUploadExcel(Cell currentCell, MtrModalidadTrabajo mtrModalidadTrabajo, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 100) {
                    throw new ServiceException("Valor Campo descripcion contiene mas de 100 caracter(es)");
                }
                mtrModalidadTrabajo.setDescripcion(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo descripcion está en formato incorrecto");
            }
            break;
        case 2:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 2) {
                    throw new ServiceException("Valor Campo status contiene mas de 2 caracter(es)");
                }
                mtrModalidadTrabajo.setStatus(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo status está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return mtrModalidadTrabajo;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected MtrModalidadTrabajo setInicializarBeanUpdateExcel() {
        MtrModalidadTrabajo bean = new MtrModalidadTrabajo();
        bean.setId(null);
        return bean;
    }

    protected final Long setObtenerId(MtrModalidadTrabajo bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final MtrModalidadTrabajo createInstance() {
        MtrModalidadTrabajo mtrModalidadTrabajo = new MtrModalidadTrabajo();
        return mtrModalidadTrabajo;
    }

    protected final BeanCargaMasivoDTO<MtrModalidadTrabajo> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<MtrModalidadTrabajo> beanCargaMasivoDTO = new BeanCargaMasivoDTO<MtrModalidadTrabajo>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrModalidadTrabajo>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrModalidadTrabajo>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrModalidadTrabajo>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(MtrModalidadTrabajo bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getDescripcion(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getStatus(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(MtrModalidadTrabajo bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getDescripcion(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getStatus(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(MtrModalidadTrabajo bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO MTR_MODALIDAD_TRABAJO(";
        sqlInsert = sqlInsert + "MTR_MODALIDAD_TRABAJO_ID" + ", ";
        sqlInsert = sqlInsert + "DESCRIPCION" + ", ";
        sqlInsert = sqlInsert + "STATUS" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        if (StringUtils.isBlank(bean.getDescripcion())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getDescripcion() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getStatus())) {
            sqlInsert = sqlInsert + "null";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getStatus() + "'";
        }
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
