/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntityDTOService.java.e.vm
 */
package com.incloud.hcp.service.impl;

import com.incloud.hcp.common.enums.AppParametriaLabelEnum;
import com.incloud.hcp.common.enums.AppParametriaModuloEnum;
import com.incloud.hcp.common.excel.ExcelDefault;
import com.incloud.hcp.domain.AppParametria;
import com.incloud.hcp.domain.MtrPuerto;
import com.incloud.hcp.domain.MtrPuerto_;
import com.incloud.hcp.domain.response.MtrPuertoResponse;
import com.incloud.hcp.exception.ServiceException;
import com.incloud.hcp.repository.delta.AppParametriaDeltaRepository;
import com.incloud.hcp.repository.delta.MtrPuertoDeltaRepository;
import com.incloud.hcp.service.MtrPuertoService;
import com.incloud.hcp.service._framework.bean.BeanCargaMasivoDTO;
import com.incloud.hcp.service._framework.bean.BeanListaMasivoDTO;
import com.incloud.hcp.service._framework.impl.JPACustomServiceImpl;
import com.incloud.hcp.service.requireNew.MtrPuertoRequireNewService;
import com.incloud.hcp.service.support.PageRequestByExample;
import com.incloud.hcp.utils.Constants;
import com.incloud.hcp.utils.PredicateUtils;
import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.lang.StringUtils;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * A simple DTO Facility for MtrPuerto.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public abstract class MtrPuertoServiceImpl extends JPACustomServiceImpl<MtrPuertoResponse, MtrPuerto, Long> implements MtrPuertoService {

    protected final String NAME_SHEET = "MtrPuerto";
    protected final String CONFIG_TITLE = "com/incloud/hcp/excel/MtrPuertoExcel.xml";
    private final Integer REGISTROS_COLOR = 10;

    @Autowired
    protected AppParametriaDeltaRepository appParametriaDeltaRepository;

    @Autowired
    protected MtrPuertoDeltaRepository mtrPuertoDeltaRepository;

    @Autowired
    protected MtrPuertoRequireNewService mtrPuertoRequireNewService;

    /*****************************/
    /* Metodos de Busqueda       */
    /*****************************/

    protected final ExampleMatcher setAbstractFind(ExampleMatcher matcher) {
        matcher = ExampleMatcher.matching() //
                .withMatcher(MtrPuerto_.codigoSapPuerto.getName(), match -> match.ignoreCase().startsWith())
                .withMatcher(MtrPuerto_.descripicon.getName(), match -> match.ignoreCase().startsWith());
        return matcher;
    }

    protected abstract Sort setFindAll(Sort sort);

    protected abstract Sort setFind(MtrPuerto req, ExampleMatcher matcher, Example<MtrPuerto> example, Sort sort);

    protected abstract void setFindPaginated(PageRequestByExample<MtrPuerto> req, ExampleMatcher matcher, Example<MtrPuerto> example);

    protected final MtrPuerto setObtenerBeanResponse(MtrPuertoResponse bean) {
        return bean.getBean();
    }

    protected final Class<MtrPuerto> setObtenerClassBean() {
        return MtrPuerto.class;
    }

    protected List<Predicate> setAbstractPredicate(MtrPuertoResponse bean, CriteriaBuilder cb, Root<MtrPuerto> root) {
        List<Predicate> predicates = new ArrayList<>();
        MtrPuerto entity = bean.getBean();
        /* Obtener condiciones */
        PredicateUtils.addPredicates(predicates, bean.getIdCondicion(), "id", entity.getId(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getCodigoSapPuertoCondicion(), "codigoSapPuerto", entity.getCodigoSapPuerto(), cb, root);
        PredicateUtils.addPredicates(predicates, bean.getDescripiconCondicion(), "descripicon", entity.getDescripicon(), cb, root);
        /* Obtener valores de Lista */
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "id", bean.getIdList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "codigoSapPuerto", bean.getCodigoSapPuertoList(), cb, root);
        PredicateUtils.addPredicatesListValorPrimitivo(predicates, "descripicon", bean.getDescripiconList(), cb, root);
        return predicates;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected final String validacionesPrevias(MtrPuerto bean) throws Exception {
        String mensaje = "";
        if (!Optional.of(bean.getDescripicon()).isPresent()) {
            String msg = this.messageSource.getMessage("message.mtrPuerto.descripicon.requerido", null, LocaleContextHolder.getLocale());
            mensaje += "* " + msg + "<br/>";
        }
        String msg = this.setValidacionesPrevias(bean);
        if (StringUtils.isNotBlank(msg)) {
            mensaje += "* " + msg + "<br/>";
        }
        return mensaje;
    }

    protected String setValidacionesPrevias(MtrPuerto bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected String validacionesPreviasCreate(MtrPuerto bean) throws Exception {
        String msg = null;
        MtrPuerto validar = null;
        return msg;
    }

    protected String validacionesPreviasSave(MtrPuerto bean) throws Exception {
        String msg = null;
        MtrPuerto validar = null;
        return msg;
    }

    protected MtrPuerto completarDatosBean(MtrPuerto bean) throws Exception {
        BigDecimal data = new BigDecimal(0.00);
        bean = this.setCompletarDatosBean(bean);
        return bean;
    }

    protected MtrPuerto setCompletarDatosBean(MtrPuerto bean) throws Exception {
        return bean;
    }

    protected final MtrPuerto setAbstractCreate(MtrPuerto dto) throws Exception {
        MtrPuerto bean = new MtrPuerto();
        bean = (MtrPuerto) BeanUtils.cloneBean(dto);
        return bean;
    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrPuerto setUploadExcel(Cell currentCell, MtrPuerto mtrPuerto, int contador) throws Exception {
        Double valorDouble = new Double(0);
        BigDecimal valorDecimal = new BigDecimal(0);
        Boolean valorBoolean = new Boolean(true);
        String valorCadena = "";
        switch (contador) {
        case 1:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 50) {
                    throw new ServiceException("Valor Campo codigoSapPuerto contiene mas de 50 caracter(es)");
                }
                mtrPuerto.setCodigoSapPuerto(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo codigoSapPuerto está en formato incorrecto");
            }
            break;
        case 2:
            try {
                valorCadena = currentCell.getStringCellValue();
                if (valorCadena.length() > 200) {
                    throw new ServiceException("Valor Campo descripicon contiene mas de 200 caracter(es)");
                }
                mtrPuerto.setDescripicon(valorCadena);
            } catch (Exception e) {
                throw new ServiceException("Valor Campo descripicon está en formato incorrecto");
            }
            break;
        default:
            break;
        }
        return mtrPuerto;
    }

    protected AppParametria setObtenerRegistroConfiguracionUploadExcel() {
        AppParametria appParametriaData = this.appParametriaDeltaRepository.getByModuloAndLabelAndStatus(AppParametriaModuloEnum.CARGA_EXCEL.getEstado(),
                AppParametriaLabelEnum.INICIO_REGISTRO_DATA.getEstado(), Constants.ESTADO_ACTIVO);
        return appParametriaData;
    }

    protected MtrPuerto setInicializarBeanUpdateExcel() {
        MtrPuerto bean = new MtrPuerto();
        bean.setId(null);
        return bean;
    }

    protected final Long setObtenerId(MtrPuerto bean) {
        return bean.getId();
    }

    /************************/
    /* Instancia de Bean    */
    /************************/

    protected final MtrPuerto createInstance() {
        MtrPuerto mtrPuerto = new MtrPuerto();
        return mtrPuerto;
    }

    protected final BeanCargaMasivoDTO<MtrPuerto> createInstanceMasivoDTO() {
        BeanCargaMasivoDTO<MtrPuerto> beanCargaMasivoDTO = new BeanCargaMasivoDTO<MtrPuerto>();
        return beanCargaMasivoDTO;

    }

    protected final BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrPuerto>> createInstanceListaMasivoDTO() {
        BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrPuerto>> beanCargaMasivoDTOBeanListaMasivoDTO = new BeanListaMasivoDTO<BeanCargaMasivoDTO<MtrPuerto>>();
        return beanCargaMasivoDTOBeanListaMasivoDTO;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected String devuelveNombreSheet() {
        return this.NAME_SHEET;
    }

    protected String devuelveListaHeaderExcelXML() {
        return this.CONFIG_TITLE;
    }

    protected int setAbstractDownloadExcel(MtrPuerto bean, HSSFRow dataRow) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getCodigoSapPuerto(), dataRow.createCell(contador));
        contador++;
        ExcelDefault.setValueCell(bean.getDescripicon(), dataRow.createCell(contador));
        contador++;
        return contador;
    }

    protected int setAbstractDownloadExcelSXLSX(MtrPuerto bean, Row dataRow, List<CellStyle> cellStyleList) {
        int contador = 0;
        ExcelDefault.setValueCell(bean.getId(), dataRow.createCell(contador), "I", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getCodigoSapPuerto(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        ExcelDefault.setValueCell(bean.getDescripicon(), dataRow.createCell(contador), "S", cellStyleList);
        contador++;
        return contador;
    }

    protected String setAbstractGenerateInsertExcelSXLSX(MtrPuerto bean) {
        String fechaS = "";
        String sqlInsert = "INSERT INTO MTR_PUERTO(";
        sqlInsert = sqlInsert + "MTR_PUERTO_ID" + ", ";
        sqlInsert = sqlInsert + "CODIGO_SAP_PUERTO" + ", ";
        sqlInsert = sqlInsert + "DESCRIPICON" + ")";
        sqlInsert = sqlInsert + " VALUES (";
        sqlInsert = sqlInsert + bean.getId() + ", ";
        if (StringUtils.isBlank(bean.getCodigoSapPuerto())) {
            sqlInsert = sqlInsert + "null" + ", ";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getCodigoSapPuerto() + "'" + ", ";
        }
        if (StringUtils.isBlank(bean.getDescripicon())) {
            sqlInsert = sqlInsert + "null";
        } else {
            sqlInsert = sqlInsert + "'" + bean.getDescripicon() + "'";
        }
        sqlInsert = sqlInsert + " );";
        return sqlInsert;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
