/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.common.BindingErrorsResponse;
import com.incloud.hcp.common.graph.GraphBean;
import com.incloud.hcp.domain.CsHistorial;
import com.incloud.hcp.domain.CsOrdenServicio;
import com.incloud.hcp.domain.MtrEstado;
import com.incloud.hcp.domain.response.CsHistorialResponse;
import com.incloud.hcp.repository.delta.CsHistorialDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import com.incloud.hcp.service.delta.CsHistorialDeltaService;
import io.swagger.annotations.ApiOperation;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Optional;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

public abstract class CsHistorialRest extends JPACustomRest<CsHistorialResponse, CsHistorial, Long> {

    @Autowired
    protected CsHistorialDeltaService csHistorialDeltaService;

    @Autowired
    protected CsHistorialDeltaRepository csHistorialDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "CsHistorial";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final CsHistorial createInstance() {
        CsHistorial csHistorial = new CsHistorial();
        return csHistorial;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    /**
    * Contador de registros para el atributo csOrdenServicio.
    */
    @ApiOperation(value = "Contador de registros para el atributo csOrdenServicio", produces = "application/json")
    @PostMapping(value = "/countByCsOrdenServicio", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByCsOrdenServicio(@RequestBody @Valid CsOrdenServicio csOrdenServicio, BindingResult bindingResult)
            throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByCsOrdenServicio");
        try {
            return Optional.ofNullable(this.csHistorialDeltaService.countByCsOrdenServicio(csOrdenServicio)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo csOrdenServicio.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo csOrdenServicio", produces = "application/json")
    @GetMapping(value = "/graphByCsOrdenServicio", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByCsOrdenServicio() throws URISyntaxException {
        log.debug("Ingresando graphByCsOrdenServicio");
        try {
            return Optional.ofNullable(this.csHistorialDeltaService.graphByCsOrdenServicio()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Contador de registros para el atributo mtrEstado.
    */
    @ApiOperation(value = "Contador de registros para el atributo mtrEstado", produces = "application/json")
    @PostMapping(value = "/countByMtrEstado", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<Long> countByMtrEstado(@RequestBody @Valid MtrEstado mtrEstado, BindingResult bindingResult) throws URISyntaxException {
        BindingErrorsResponse errors = new BindingErrorsResponse();
        HttpHeaders headers = new HttpHeaders();
        if (bindingResult.hasErrors()) {
            errors.addAllErrors(bindingResult);
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(errors.toJSON());
            }
            headers.add("errors", errors.toJSON());
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
        log.debug("Ingresando countByMtrEstado");
        try {
            return Optional.ofNullable(this.csHistorialDeltaService.countByMtrEstado(mtrEstado)).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

    /**
    * Genera Grafico de registros para el atributo mtrEstado.
    */
    @ApiOperation(value = "Genera Grafico de registros para el atributo mtrEstado", produces = "application/json")
    @GetMapping(value = "/graphByMtrEstado", produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<GraphBean> graphByMtrEstado() throws URISyntaxException {
        log.debug("Ingresando graphByMtrEstado");
        try {
            return Optional.ofNullable(this.csHistorialDeltaService.graphByMtrEstado()).map(l -> new ResponseEntity<>(l, HttpStatus.OK))
                    .orElse(new ResponseEntity<>(HttpStatus.NO_CONTENT));
        } catch (Exception e) {
            if (this.devuelveRuntimeException) {
                throw new RuntimeException(e);
            }
            HttpHeaders headers = this.devuelveErrorHeaders(e);
            return new ResponseEntity<>(headers, HttpStatus.BAD_REQUEST);
        }
    }

}
