/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrCalidadServicio;
import com.incloud.hcp.domain.response.MtrCalidadServicioResponse;
import com.incloud.hcp.repository.delta.MtrCalidadServicioDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrCalidadServicioRest extends JPACustomRest<MtrCalidadServicioResponse, MtrCalidadServicio, Long> {

    @Autowired
    protected MtrCalidadServicioDeltaRepository mtrCalidadServicioDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrCalidadServicio";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrCalidadServicio createInstance() {
        MtrCalidadServicio mtrCalidadServicio = new MtrCalidadServicio();
        return mtrCalidadServicio;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
