/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrLugarTrabajo;
import com.incloud.hcp.domain.response.MtrLugarTrabajoResponse;
import com.incloud.hcp.repository.delta.MtrLugarTrabajoDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrLugarTrabajoRest extends JPACustomRest<MtrLugarTrabajoResponse, MtrLugarTrabajo, Long> {

    @Autowired
    protected MtrLugarTrabajoDeltaRepository mtrLugarTrabajoDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrLugarTrabajo";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrLugarTrabajo createInstance() {
        MtrLugarTrabajo mtrLugarTrabajo = new MtrLugarTrabajo();
        return mtrLugarTrabajo;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
