/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrSeguridad;
import com.incloud.hcp.domain.response.MtrSeguridadResponse;
import com.incloud.hcp.repository.delta.MtrSeguridadDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrSeguridadRest extends JPACustomRest<MtrSeguridadResponse, MtrSeguridad, Long> {

    @Autowired
    protected MtrSeguridadDeltaRepository mtrSeguridadDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrSeguridad";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrSeguridad createInstance() {
        MtrSeguridad mtrSeguridad = new MtrSeguridad();
        return mtrSeguridad;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
