/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/rest/EntityResource.java.e.vm
 */
package com.incloud.hcp.rest;

import com.incloud.hcp.domain.MtrUnidadMedida;
import com.incloud.hcp.domain.response.MtrUnidadMedidaResponse;
import com.incloud.hcp.repository.delta.MtrUnidadMedidaDeltaRepository;
import com.incloud.hcp.rest._framework.JPACustomRest;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class MtrUnidadMedidaRest extends JPACustomRest<MtrUnidadMedidaResponse, MtrUnidadMedida, Long> {

    @Autowired
    protected MtrUnidadMedidaDeltaRepository mtrUnidadMedidaDeltaRepository;

    protected String setObtenerNombreArchivoExcel() {
        return "MtrUnidadMedida";
    }

    /************************/
    /* Instancia de Bean    */
    /************************/
    protected final MtrUnidadMedida createInstance() {
        MtrUnidadMedida mtrUnidadMedida = new MtrUnidadMedida();
        return mtrUnidadMedida;
    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
