/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.BaseResponseDomain;
import com.incloud.hcp.domain.CsHistorial;
import com.incloud.hcp.domain.CsOrdenServicio;
import com.incloud.hcp.domain.MtrEstado;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;
import java.util.List;

/**
 * Simple Interface for CsHistorial.
 */
@Data
@ToString
@EqualsAndHashCode
public class CsHistorialResponse extends BaseResponseDomain<CsHistorial> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String descripcionCondicion;
    private String usuarioHistorialCondicion;
    private String fechaHistorialCondicion;
    //private String csOrdenServicioCondicion;
    //private String mtrEstadoCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Long> idList;
    private List<String> descripcionList;
    private List<String> usuarioHistorialList;
    private List<Date> fechaHistorialList;
    private List<CsOrdenServicio> csOrdenServicioList;
    private List<MtrEstado> mtrEstadoList;

}
