/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.BaseResponseDomain;
import com.incloud.hcp.domain.CsMaterial;
import com.incloud.hcp.domain.CsOrdenServicio;
import com.incloud.hcp.domain.MtrUnidadMedida;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.math.BigDecimal;
import java.util.List;

/**
 * Simple Interface for CsMaterial.
 */
@Data
@ToString
@EqualsAndHashCode
public class CsMaterialResponse extends BaseResponseDomain<CsMaterial> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String codigoMaterialCondicion;
    private String descripcionMaterialCondicion;
    private String cantidadCondicion;
    //private String mtrUnidadMedidaCondicion;
    //private String csOrdenServicioCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Long> idList;
    private List<String> codigoMaterialList;
    private List<String> descripcionMaterialList;
    private List<BigDecimal> cantidadList;
    private List<MtrUnidadMedida> mtrUnidadMedidaList;
    private List<CsOrdenServicio> csOrdenServicioList;

}
