/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityResponse.java.e.vm
 */
package com.incloud.hcp.domain.response;

import com.incloud.hcp.domain.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

import java.util.Date;
import java.util.List;

/**
 * Simple Interface for CsOrdenServicio.
 */
@Data
@ToString
@EqualsAndHashCode
public class CsOrdenServicioResponse extends BaseResponseDomain<CsOrdenServicio> {

    /****************************/
    /* Variables de Condiciones */
    /****************************/

    private String idCondicion;
    private String numeroOrdenServicioCondicion;
    private String fechaEmisionCondicion;
    private String motivoCondicion;
    private String txtAprobacionCondicion;
    private String horometroCondicion;
    private String fechaInicioDuracionRealCondicion;
    private String horaInicioDuracionRealCondicion;
    private String fechaFinDuracionRealCondicion;
    private String horaFinDuracionRealCondicion;
    private String codigoSistemaCondicion;
    private String descripcionSistemaCondicion;
    private String codigoEmbarcacionCondicion;
    private String descripcionEmbarcacionCondicion;
    private String claseOdmCondicion;
    private String rucProveedorCondicion;
    private String razonSocialProveedorCondicion;
    private String lifnrProveedorCondicion;
    private String observacionCondicion;
    private String codigoEquipoCondicion;
    private String descripcionEquipoCondicion;
    //private String mtrModalidadTrabajoCondicion;
    //private String mtrTiempoEntregaCondicion;
    //private String mtrCalidadServicioCondicion;
    //private String mtrEstadoCondicion;
    //private String mtrLugarTrabajoCondicion;
    //private String odmCondicion;
    //private String mtrPuertoCondicion;
    //private String mtrSeguridadCondicion;

    /****************************/
    /* Variables Listas         */
    /****************************/

    private List<Long> idList;
    private List<String> numeroOrdenServicioList;
    private List<Date> fechaEmisionList;
    private List<String> motivoList;
    private List<String> txtAprobacionList;
    private List<String> horometroList;
    private List<Date> fechaInicioDuracionRealList;
    private List<String> horaInicioDuracionRealList;
    private List<Date> fechaFinDuracionRealList;
    private List<String> horaFinDuracionRealList;
    private List<String> codigoSistemaList;
    private List<String> descripcionSistemaList;
    private List<String> codigoEmbarcacionList;
    private List<String> descripcionEmbarcacionList;
    private List<String> claseOdmList;
    private List<String> rucProveedorList;
    private List<String> razonSocialProveedorList;
    private List<String> lifnrProveedorList;
    private List<String> observacionList;
    private List<String> codigoEquipoList;
    private List<String> descripcionEquipoList;
    private List<MtrModalidadTrabajo> mtrModalidadTrabajoList;
    private List<MtrTiempoEntrega> mtrTiempoEntregaList;
    private List<MtrCalidadServicio> mtrCalidadServicioList;
    private List<MtrEstado> mtrEstadoList;
    private List<MtrLugarTrabajo> mtrLugarTrabajoList;
    private List<Odm> odmList;
    private List<MtrPuerto> mtrPuertoList;
    private List<MtrSeguridad> mtrSeguridadList;

}
