/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(CsAdjunto.class)
public abstract class CsAdjunto_ {

    // Raw attributes
    public static volatile SingularAttribute<CsAdjunto, Long> id;
    public static volatile SingularAttribute<CsAdjunto, String> numeroOds;
    public static volatile SingularAttribute<CsAdjunto, String> extension;
    public static volatile SingularAttribute<CsAdjunto, String> descProveedor;
    public static volatile SingularAttribute<CsAdjunto, String> documentoRepositorioId;

    // Many to one
    public static volatile SingularAttribute<CsAdjunto, MtrTipoDocumento> mtrTipoDocumento;
    public static volatile SingularAttribute<CsAdjunto, CsOrdenServicio> csOrdenServicio;
}
