/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.util.Date;

@StaticMetamodel(CsHistorial.class)
public abstract class CsHistorial_ {

    // Raw attributes
    public static volatile SingularAttribute<CsHistorial, Long> id;
    public static volatile SingularAttribute<CsHistorial, String> descripcion;
    public static volatile SingularAttribute<CsHistorial, String> usuarioHistorial;
    public static volatile SingularAttribute<CsHistorial, Date> fechaHistorial;

    // Many to one
    public static volatile SingularAttribute<CsHistorial, CsOrdenServicio> csOrdenServicio;
    public static volatile SingularAttribute<CsHistorial, MtrEstado> mtrEstado;
}
