/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.Date;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;
import static javax.persistence.TemporalType.TIMESTAMP;

@Entity
@Table(name = "CS_HISTORIAL")
//@Audited
//@AuditTable("_audi_CS_HISTORIAL")
public class CsHistorial extends BaseDomain implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(CsHistorial.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Long id;
    private String descripcion;
    private String usuarioHistorial;
    private Date fechaHistorial;

    // Many to one
    private CsOrdenServicio csOrdenServicio;
    private MtrEstado mtrEstado;

    @Override
    public String entityClassName() {
        return CsHistorial.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "CS_HISTORIAL_ID", precision = 19)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_CS_HISTORIAL")
    @Id
    @SequenceGenerator(name = "seq_CS_HISTORIAL", sequenceName = "seq_CS_HISTORIAL", allocationSize = 1)
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public CsHistorial id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [descripcion] ------------------------

    @Size(max = 255, message = "{message.csHistorial.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "DESCRIPCION")
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public CsHistorial descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }
    // -- [usuarioHistorial] ------------------------

    @NotEmpty(message = "{message.csHistorial.usuarioHistorial.requerido}")
    @Size(max = 100, message = "{message.csHistorial.usuarioHistorial.sizeMax} {max} {message.caracter}")
    @Column(name = "USUARIO_HISTORIAL", nullable = false, length = 100)
    public String getUsuarioHistorial() {
        return usuarioHistorial;
    }

    public void setUsuarioHistorial(String usuarioHistorial) {
        this.usuarioHistorial = usuarioHistorial;
    }

    public CsHistorial usuarioHistorial(String usuarioHistorial) {
        setUsuarioHistorial(usuarioHistorial);
        return this;
    }
    // -- [fechaHistorial] ------------------------

    @NotNull
    @Column(name = "FECHA_HISTORIAL", nullable = false, length = 29)

    @Temporal(TIMESTAMP)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd/MM/yyyy")
    public Date getFechaHistorial() {
        return fechaHistorial;
    }

    public void setFechaHistorial(Date fechaHistorial) {
        this.fechaHistorial = fechaHistorial;
    }

    public CsHistorial fechaHistorial(Date fechaHistorial) {
        setFechaHistorial(fechaHistorial);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CsHistorial.csOrdenServicio ==> CsOrdenServicio.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "CS_ORDEN_SERVICIO_ID", nullable = false)
    @ManyToOne
    public CsOrdenServicio getCsOrdenServicio() {
        return csOrdenServicio;
    }

    /**
     * Set the {@link #csOrdenServicio} without adding this CsHistorial instance on the passed {@link #csOrdenServicio}
     */
    public void setCsOrdenServicio(CsOrdenServicio csOrdenServicio) {
        this.csOrdenServicio = csOrdenServicio;
    }

    public CsHistorial csOrdenServicio(CsOrdenServicio csOrdenServicio) {
        setCsOrdenServicio(csOrdenServicio);
        return this;
    }

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CsHistorial.mtrEstado ==> MtrEstado.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "MTR_ESTADO_ID", nullable = false)
    @ManyToOne
    public MtrEstado getMtrEstado() {
        return mtrEstado;
    }

    /**
     * Set the {@link #mtrEstado} without adding this CsHistorial instance on the passed {@link #mtrEstado}
     */
    public void setMtrEstado(MtrEstado mtrEstado) {
        this.mtrEstado = mtrEstado;
    }

    public CsHistorial mtrEstado(MtrEstado mtrEstado) {
        setMtrEstado(mtrEstado);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CsHistorial withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CsHistorial && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this CsHistorial instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("descripcion", getDescripcion()) //
                .add("usuarioHistorial", getUsuarioHistorial()) //
                .add("fechaHistorial", getFechaHistorial()) //
                .add("mtrEstado", getMtrEstado()) //    
                .add("csOrdenServicio", getCsOrdenServicio()) //    
                .toString();
    }
}
