/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "CS_ORDEN_SERVICIO_ACTIVIDAD")
//@Audited
//@AuditTable("_audi_CS_ORDEN_SERVICIO_ACTIVIDAD")
public class CsOrdenServicioActividad extends BaseDomain implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(CsOrdenServicioActividad.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Long id;
    private String descripcion;

    // Many to one
    private CsOrdenServicio csOrdenServicio;

    @Override
    public String entityClassName() {
        return CsOrdenServicioActividad.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "CS_ORDEN_SERVICIO_ACTIVIDAD_ID", precision = 19)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_CS_ORDEN_SERVICIO_ACTIVIDAD")
    @Id
    @SequenceGenerator(name = "seq_CS_ORDEN_SERVICIO_ACTIVIDAD", sequenceName = "seq_CS_ORDEN_SERVICIO_ACTIVIDAD", allocationSize = 1)
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public CsOrdenServicioActividad id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [descripcion] ------------------------

    @NotEmpty(message = "{message.csOrdenServicioActividad.descripcion.requerido}")
    @Size(max = 100, message = "{message.csOrdenServicioActividad.descripcion.sizeMax} {max} {message.caracter}")
    @Column(name = "DESCRIPCION", nullable = false, length = 100)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public CsOrdenServicioActividad descripcion(String descripcion) {
        setDescripcion(descripcion);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: CsOrdenServicioActividad.csOrdenServicio ==> CsOrdenServicio.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "CS_ORDEN_SERVICIO_ID", nullable = false)
    @ManyToOne
    public CsOrdenServicio getCsOrdenServicio() {
        return csOrdenServicio;
    }

    /**
     * Set the {@link #csOrdenServicio} without adding this CsOrdenServicioActividad instance on the passed {@link #csOrdenServicio}
     */
    public void setCsOrdenServicio(CsOrdenServicio csOrdenServicio) {
        this.csOrdenServicio = csOrdenServicio;
    }

    public CsOrdenServicioActividad csOrdenServicio(CsOrdenServicio csOrdenServicio) {
        setCsOrdenServicio(csOrdenServicio);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CsOrdenServicioActividad withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CsOrdenServicioActividad && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this CsOrdenServicioActividad instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("descripcion", getDescripcion()) //
                .add("csOrdenServicio", getCsOrdenServicio()) //    
                .toString();
    }
}
