/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;
import java.util.Date;

@StaticMetamodel(CsOrdenServicio.class)
public abstract class CsOrdenServicio_ {

    // Raw attributes
    public static volatile SingularAttribute<CsOrdenServicio, Long> id;
    public static volatile SingularAttribute<CsOrdenServicio, String> numeroOrdenServicio;
    public static volatile SingularAttribute<CsOrdenServicio, Date> fechaEmision;
    public static volatile SingularAttribute<CsOrdenServicio, String> motivo;
    public static volatile SingularAttribute<CsOrdenServicio, String> txtAprobacion;
    public static volatile SingularAttribute<CsOrdenServicio, String> horometro;
    public static volatile SingularAttribute<CsOrdenServicio, Date> fechaInicioDuracionReal;
    public static volatile SingularAttribute<CsOrdenServicio, String> horaInicioDuracionReal;
    public static volatile SingularAttribute<CsOrdenServicio, Date> fechaFinDuracionReal;
    public static volatile SingularAttribute<CsOrdenServicio, String> horaFinDuracionReal;
    public static volatile SingularAttribute<CsOrdenServicio, String> codigoSistema;
    public static volatile SingularAttribute<CsOrdenServicio, String> descripcionSistema;
    public static volatile SingularAttribute<CsOrdenServicio, String> codigoEmbarcacion;
    public static volatile SingularAttribute<CsOrdenServicio, String> descripcionEmbarcacion;
    public static volatile SingularAttribute<CsOrdenServicio, String> claseOdm;
    public static volatile SingularAttribute<CsOrdenServicio, String> rucProveedor;
    public static volatile SingularAttribute<CsOrdenServicio, String> razonSocialProveedor;
    public static volatile SingularAttribute<CsOrdenServicio, String> lifnrProveedor;
    public static volatile SingularAttribute<CsOrdenServicio, String> observacion;
    public static volatile SingularAttribute<CsOrdenServicio, String> codigoEquipo;
    public static volatile SingularAttribute<CsOrdenServicio, String> descripcionEquipo;

    // Many to one
    public static volatile SingularAttribute<CsOrdenServicio, MtrModalidadTrabajo> mtrModalidadTrabajo;
    public static volatile SingularAttribute<CsOrdenServicio, MtrTiempoEntrega> mtrTiempoEntrega;
    public static volatile SingularAttribute<CsOrdenServicio, MtrCalidadServicio> mtrCalidadServicio;
    public static volatile SingularAttribute<CsOrdenServicio, MtrEstado> mtrEstado;
    public static volatile SingularAttribute<CsOrdenServicio, MtrLugarTrabajo> mtrLugarTrabajo;
    public static volatile SingularAttribute<CsOrdenServicio, Odm> odm;
    public static volatile SingularAttribute<CsOrdenServicio, MtrPuerto> mtrPuerto;
    public static volatile SingularAttribute<CsOrdenServicio, MtrSeguridad> mtrSeguridad;
}
