/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "MTR_PUERTO")
//@Audited
//@AuditTable("_audi_MTR_PUERTO")
public class MtrPuerto extends BaseDomain implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MtrPuerto.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Long id;
    private String codigoSapPuerto;
    private String descripicon;

    @Override
    public String entityClassName() {
        return MtrPuerto.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "MTR_PUERTO_ID", precision = 19)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_MTR_PUERTO")
    @Id
    @SequenceGenerator(name = "seq_MTR_PUERTO", sequenceName = "seq_MTR_PUERTO", allocationSize = 1)
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public MtrPuerto id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codigoSapPuerto] ------------------------

    @Size(max = 50, message = "{message.mtrPuerto.codigoSapPuerto.sizeMax} {max} {message.caracter}")
    @Column(name = "CODIGO_SAP_PUERTO", length = 50)
    public String getCodigoSapPuerto() {
        return codigoSapPuerto;
    }

    public void setCodigoSapPuerto(String codigoSapPuerto) {
        this.codigoSapPuerto = codigoSapPuerto;
    }

    public MtrPuerto codigoSapPuerto(String codigoSapPuerto) {
        setCodigoSapPuerto(codigoSapPuerto);
        return this;
    }
    // -- [descripicon] ------------------------

    @NotEmpty(message = "{message.mtrPuerto.descripicon.requerido}")
    @Size(max = 200, message = "{message.mtrPuerto.descripicon.sizeMax} {max} {message.caracter}")
    @Column(name = "DESCRIPICON", nullable = false, length = 200)
    public String getDescripicon() {
        return descripicon;
    }

    public void setDescripicon(String descripicon) {
        this.descripicon = descripicon;
    }

    public MtrPuerto descripicon(String descripicon) {
        setDescripicon(descripicon);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MtrPuerto withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MtrPuerto && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this MtrPuerto instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codigoSapPuerto", getCodigoSapPuerto()) //
                .add("descripicon", getDescripicon()) //
                .toString();
    }
}
