/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.incloud.hcp.domain;

import com.google.common.base.MoreObjects;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.util.logging.Logger;

import static javax.persistence.GenerationType.SEQUENCE;

@Entity
@Table(name = "ODM")
//@Audited
//@AuditTable("_audi_ODM")
public class Odm extends BaseDomain implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Odm.class.getName());

    /***************************/
    /* Atributos de la Entidad */
    /***************************/

    // Raw attributes
    private Long id;
    private String codigoEquipoSap;
    private String codigoProveedorSap;

    @Override
    public String entityClassName() {
        return Odm.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "ODM_ID", precision = 19)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_ODM")
    @Id
    @SequenceGenerator(name = "seq_ODM", sequenceName = "seq_ODM", allocationSize = 1)
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Odm id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [codigoEquipoSap] ------------------------

    @Size(max = 18, message = "{message.odm.codigoEquipoSap.sizeMax} {max} {message.caracter}")
    @Column(name = "CODIGO_EQUIPO_SAP", length = 18)
    public String getCodigoEquipoSap() {
        return codigoEquipoSap;
    }

    public void setCodigoEquipoSap(String codigoEquipoSap) {
        this.codigoEquipoSap = codigoEquipoSap;
    }

    public Odm codigoEquipoSap(String codigoEquipoSap) {
        setCodigoEquipoSap(codigoEquipoSap);
        return this;
    }
    // -- [codigoProveedorSap] ------------------------

    @Size(max = 10, message = "{message.odm.codigoProveedorSap.sizeMax} {max} {message.caracter}")
    @Column(name = "CODIGO_PROVEEDOR_SAP", length = 10)
    public String getCodigoProveedorSap() {
        return codigoProveedorSap;
    }

    public void setCodigoProveedorSap(String codigoProveedorSap) {
        this.codigoProveedorSap = codigoProveedorSap;
    }

    public Odm codigoProveedorSap(String codigoProveedorSap) {
        setCodigoProveedorSap(codigoProveedorSap);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Odm withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Odm && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Odm instance.
     * @see Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("codigoEquipoSap", getCodigoEquipoSap()) //
                .add("codigoProveedorSap", getCodigoProveedorSap()) //
                .toString();
    }
}
