/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.incloud.hcp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Odm.class)
public abstract class Odm_ {

    // Raw attributes
    public static volatile SingularAttribute<Odm, Long> id;
    public static volatile SingularAttribute<Odm, String> codigoEquipoSap;
    public static volatile SingularAttribute<Odm, String> codigoProveedorSap;
}
