/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.*;
import com.incloud.hcp.domain.response.CsOrdenServicioResponse;
import com.incloud.hcp.service.delta.CsOrdenServicioDeltaService;
import com.incloud.hcp.service.impl.CsOrdenServicioServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for CsOrdenServicio.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class CsOrdenServicioDeltaServiceImpl extends CsOrdenServicioServiceImpl implements CsOrdenServicioDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "descripcionEquipo"));
        return sort;
    }

    protected Sort setFind(CsOrdenServicio req, ExampleMatcher matcher, Example<CsOrdenServicio> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "descripcionEquipo"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<CsOrdenServicio> req, ExampleMatcher matcher, Example<CsOrdenServicio> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, CsOrdenServicioResponse bean, CriteriaBuilder cb,
            CriteriaQuery<CsOrdenServicio> query, Root<CsOrdenServicio> root) throws Exception {

        CsOrdenServicio entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<CsOrdenServicio, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<CsOrdenServicio, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<CsOrdenServicio> setAdicionalDeltaTotalPredicate(CsOrdenServicioResponse bean, Root<CsOrdenServicio> countRoot) throws Exception {
        CsOrdenServicio entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<CsOrdenServicio, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(CsOrdenServicio bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected CsOrdenServicio setCreate(CsOrdenServicio bean) throws Exception {
        return bean;
    }

    protected void setSave(CsOrdenServicio dto) throws Exception {
        return;
    }

    protected void setDelete(Long id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected CsOrdenServicio setUploadExcel(Cell currentCell, CsOrdenServicio csOrdenServicio, int contador) throws Exception {
        csOrdenServicio = super.setUploadExcel(currentCell, csOrdenServicio, contador);
        return csOrdenServicio;
    }

    protected String setSaveMasivo(CsOrdenServicio dto) throws Exception {
        return "";
    }

    protected List<CsOrdenServicio> setBeforeDeleteMasivo(List<CsOrdenServicio> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(CsOrdenServicio bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

    protected String setGraphDescripcionByMtrModalidadTrabajo(MtrModalidadTrabajo mtrModalidadTrabajo) {
        return mtrModalidadTrabajo.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrModalidadTrabajo() {
        return "MtrModalidadTrabajo";
    }

    protected String setGraphBarChartTituloByMtrModalidadTrabajo() {
        return "MtrModalidadTrabajo";
    }

    protected String setGraphDescripcionByMtrTiempoEntrega(MtrTiempoEntrega mtrTiempoEntrega) {
        return mtrTiempoEntrega.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrTiempoEntrega() {
        return "MtrTiempoEntrega";
    }

    protected String setGraphBarChartTituloByMtrTiempoEntrega() {
        return "MtrTiempoEntrega";
    }

    protected String setGraphDescripcionByMtrCalidadServicio(MtrCalidadServicio mtrCalidadServicio) {
        return mtrCalidadServicio.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrCalidadServicio() {
        return "MtrCalidadServicio";
    }

    protected String setGraphBarChartTituloByMtrCalidadServicio() {
        return "MtrCalidadServicio";
    }

    protected String setGraphDescripcionByMtrEstado(MtrEstado mtrEstado) {
        return mtrEstado.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrEstado() {
        return "MtrEstado";
    }

    protected String setGraphBarChartTituloByMtrEstado() {
        return "MtrEstado";
    }

    protected String setGraphDescripcionByMtrLugarTrabajo(MtrLugarTrabajo mtrLugarTrabajo) {
        return mtrLugarTrabajo.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrLugarTrabajo() {
        return "MtrLugarTrabajo";
    }

    protected String setGraphBarChartTituloByMtrLugarTrabajo() {
        return "MtrLugarTrabajo";
    }

    protected String setGraphDescripcionByOdm(Odm odm) {
        return odm.getId().toString();
    }

    protected String setGraphPieChartTituloByOdm() {
        return "Odm";
    }

    protected String setGraphBarChartTituloByOdm() {
        return "Odm";
    }

    protected String setGraphDescripcionByMtrPuerto(MtrPuerto mtrPuerto) {
        return mtrPuerto.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrPuerto() {
        return "MtrPuerto";
    }

    protected String setGraphBarChartTituloByMtrPuerto() {
        return "MtrPuerto";
    }

    protected String setGraphDescripcionByMtrSeguridad(MtrSeguridad mtrSeguridad) {
        return mtrSeguridad.getId().toString();
    }

    protected String setGraphPieChartTituloByMtrSeguridad() {
        return "MtrSeguridad";
    }

    protected String setGraphBarChartTituloByMtrSeguridad() {
        return "MtrSeguridad";
    }

}
