/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Modificado por CARLOS BAZALAR
 * Email: cbazalarlarosa@gmail.com
 * Template pack-angular:src/main/java/dto/EntitydeltaDTOService.java.e.vm
 */
package com.incloud.hcp.service.delta.impl;

import com.incloud.hcp.domain.MtrLugarTrabajo;
import com.incloud.hcp.domain.response.MtrLugarTrabajoResponse;
import com.incloud.hcp.service.delta.MtrLugarTrabajoDeltaService;
import com.incloud.hcp.service.impl.MtrLugarTrabajoServiceImpl;
import com.incloud.hcp.service.support.PageRequestByExample;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.ss.usermodel.Cell;
import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;
import java.util.List;

/**
 * A simple DTO Facility for MtrLugarTrabajo.
 */
@Service
@Transactional(propagation = Propagation.REQUIRED, rollbackFor = Exception.class)
public class MtrLugarTrabajoDeltaServiceImpl extends MtrLugarTrabajoServiceImpl implements MtrLugarTrabajoDeltaService {

    /**************************/
    /* Metodos Personalizados */
    /**************************/

    /***********************/
    /* Metodos de Busqueda */
    /***********************/

    protected Sort setFindAll(Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "descripcion"));
        return sort;
    }

    protected Sort setFind(MtrLugarTrabajo req, ExampleMatcher matcher, Example<MtrLugarTrabajo> example, Sort sort) {
        sort = Sort.by(new Sort.Order(Sort.Direction.ASC, "descripcion"));
        return sort;
    }

    protected void setFindPaginated(PageRequestByExample<MtrLugarTrabajo> req, ExampleMatcher matcher, Example<MtrLugarTrabajo> example) {
        return;
    }

    protected List<Predicate> setAdicionalDeltaPredicate(List<Predicate> predicates, MtrLugarTrabajoResponse bean, CriteriaBuilder cb,
            CriteriaQuery<MtrLugarTrabajo> query, Root<MtrLugarTrabajo> root) throws Exception {

        MtrLugarTrabajo entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            Join<MtrLugarTrabajo, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
        
            if (Optional.ofNullable(entity.get<VariableManytoOne>().get<Atributo>()).isPresent()) {
                Join<MtrLugarTrabajo, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
                Predicate thirdCondition = cb.equal(from<ClaseManytoOne>.get("<Atributo>"), entity.get<ClaseManytoOne>().get<Atributo>());
                predicates.add(thirdCondition);
            }
            
        }
        query.orderBy(cb.desc(root.get("<campo entity>")));
        */
        return predicates;
    }

    protected Root<MtrLugarTrabajo> setAdicionalDeltaTotalPredicate(MtrLugarTrabajoResponse bean, Root<MtrLugarTrabajo> countRoot) throws Exception {
        MtrLugarTrabajo entity = bean.getBean();
        //Ejemplo
        /*
        if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
            if (Optional.ofNullable(entity.get<VariableManytoOne>()).isPresent()) {
                Join<MtrLugarTrabajo, <ClaseManytoOne>> from<ClaseManytoOne> = countRoot.join("<variableManytoOne>", JoinType.INNER);
            }
        }
        */
        return countRoot;
    }

    /****************/
    /* METODOS CRUD */
    /****************/

    protected String setValidacionesPrevias(MtrLugarTrabajo bean) throws Exception {
        String mensaje = "";
        return mensaje;
    }

    protected MtrLugarTrabajo setCreate(MtrLugarTrabajo bean) throws Exception {
        return bean;
    }

    protected void setSave(MtrLugarTrabajo dto) throws Exception {
        return;
    }

    protected void setDelete(Long id) throws Exception {

    }

    protected void setDeleteAll() throws Exception {

    }

    /************************/
    /* METODOS CRUD Masivos */
    /************************/

    protected MtrLugarTrabajo setUploadExcel(Cell currentCell, MtrLugarTrabajo mtrLugarTrabajo, int contador) throws Exception {
        mtrLugarTrabajo = super.setUploadExcel(currentCell, mtrLugarTrabajo, contador);
        return mtrLugarTrabajo;
    }

    protected String setSaveMasivo(MtrLugarTrabajo dto) throws Exception {
        return "";
    }

    protected List<MtrLugarTrabajo> setBeforeDeleteMasivo(List<MtrLugarTrabajo> listaDto) throws Exception {
        return listaDto;
    }

    protected void setAfterDeleteMasivo() throws Exception {
        return;
    }

    /*****************************/
    /* Metodos que generan Excel */
    /*****************************/

    protected void setDownloadExcelItem(MtrLugarTrabajo bean, HSSFRow dataRow) {

    }

    protected void setDownloadExcel(HSSFSheet sheet) {

    }

    /*****************/
    /* Otros Metodos */
    /*****************/

}
